### ISSUE TITLE
Like Button について

### ISSUE THREAD

**Issue by liuchiawei** [AnhNangCuaEm/Deep-Shinjuku#17]
今のlikes.phpとupdate_likes.phpについて、
この二つの機能を function.php にまとめて書くことはできますか？
それと、likes_data のデータを新しいクラスで書き直すことはできますか？（例えばStoryLikes.php,StoryLikesData.php）
またよろしくお願いします。
@AnhNangCuaEm

**Comment by AnhNangCuaEm** [comment]
likeとupdatelikeをLikemanager.php にまとめてclassで書き直しました。
私のbranchを見てみてください

**Comment by liuchiawei** [comment]
はい、では実装してみてね。
story.phpの<button class="like-button">がクリックと、`data/likes_data.json`のデータと、`<div class="like-count" id="likeCount">`の中の数字も更新したい（+1）と思います。
また、もう一回クリックと戻る（-1）こともやりたいと思います。
またよろしくお願いします。
