### ISSUE TITLE
隠し要素について

### ISSUE THREAD

**Issue by liuchiawei** [AnhNangCuaEm/Deep-Shinjuku#23]
今、25個の怪談を全部読み終えた後に、何かちょっとした“おまけ”を用意できたら面白いかなと考えているんですが、具体的にどんなものにするかはまだ思いついていません。何かみんなのアイデアで『これ、面白そう！』と思うものがあれば、ぜひ教えてほしいです！

**Comment by AnhNangCuaEm** [comment]
DevToolsで何かを入れたらどうですか?!

**Comment by liuchiawei** [comment]
すみません、DevToolsって何のことかちょっと分からないんですが、もう少し詳しく教えてもらえますか？ごめんなさい！

**Comment by AnhNangCuaEm** [comment]
デベロッパーツールの中で何か面白いもの(easter egg)を入れたら面白いと思うことです。F12キーを押さないと見つけられないのeaster eggのようなものと思っています。

**Comment by liuchiawei** [comment]
なるほど、これもいいですね。面白そうです・
