### ISSUE TITLE
Likes Function

### ISSUE THREAD

**Issue by liuchiawei** [AnhNangCuaEm/Deep-Shinjuku#5]
Likeについて、今のdata.jsonじゃあなくて、他のファイルに保存したほうがいいと思います。
今後、コメント機能もやりたいから、like や comment などを他のjsonに保存するのはどう思いますか？

**Comment by AnhNangCuaEm** [comment]
今のstories.jsonにある"likes": "0"消して
id,like,commentの保存する(likes_comment_data.json)のようなファイルを作ればいいですか

**Comment by liuchiawei** [comment]
そうですね、多分commentのidとauthorも一緒に作るがいいと思います。よろしくお願いします。
