### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by liuchiawei** [AnhNangCuaEm/Deep-Shinjuku#7]
今後の開発では、機能ごとにブランチを作成するのが良いかと考えています。例えば、features/css や features/intro_animation といった形です。または、開発者の名前で分ける方法もあり、例えば dev/liu のようなブランチ名です。この方が管理しやすいかもしれませんが、どう思いますか？

**Comment by AnhNangCuaEm** [comment]
それでいいと思います。

**Comment by liuchiawei** [comment]
それでは、私のメールをManage accessに入ってもいいですか？
doublecheap@gmail.com
自分の branch を作りたいから、
よろしくお願いします。
